apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-statestore-pg-v2
spec:
  type: state.postgresql
  initTimeout: 60s
  version: v2
  metadata:
    # Connection string
    - name: connectionString
      value: "host=postgres-db user=postgres password=postgres port=5432 database=postgres"
    - name: actorStateStore
      value: "true"
    - name: tablePrefix
      value: v2_